"""
Binary Tree Traversal Implementation

This module provides a complete binary tree data structure with three traversal methods:
- Preorder (Root -> Left -> Right)
- Inorder (Left -> Root -> Right)
- Postorder (Left -> Right -> Root)

Each traversal is implemented in both recursive and iterative approaches.

Author: Generated by 小fancy
Date: 2026-03-02
"""

from typing import List, Optional
from collections import deque


class TreeNode:
    """
    Binary tree node class.
    
    Attributes:
        val: The value stored in the node
        left: Reference to the left child node
        right: Reference to the right child node
    """
    
    def __init__(self, val: int = 0, left: Optional['TreeNode'] = None, right: Optional['TreeNode'] = None):
        """
        Initialize a tree node.
        
        Args:
            val: Node value
            left: Left child node
            right: Right child node
        """
        self.val = val
        self.left = left
        self.right = right
    
    def __repr__(self) -> str:
        return f"TreeNode({self.val})"


class BinaryTree:
    """
    Binary tree class with various traversal methods.
    """
    
    def __init__(self, root: Optional[TreeNode] = None):
        """
        Initialize a binary tree.
        
        Args:
            root: Root node of the tree
        """
        self.root = root
    
    # ==================== Preorder Traversal ====================
    
    def preorder_recursive(self, node: Optional[TreeNode] = None) -> List[int]:
        """
        Preorder traversal using recursion (Root -> Left -> Right).
        
        Time Complexity: O(n)
        Space Complexity: O(h) where h is the height of the tree
        
        Args:
            node: Starting node (defaults to root)
            
        Returns:
            List of node values in preorder
            
        Example:
            >>> tree = BinaryTree.from_list([1, 2, 3, 4, 5])
            >>> tree.preorder_recursive()
            [1, 2, 4, 5, 3]
        """
        if node is None:
            node = self.root
        
        result = []
        
        def traverse(n: Optional[TreeNode]):
            if n is None:
                return
            result.append(n.val)  # Visit root
            traverse(n.left)       # Traverse left
            traverse(n.right)      # Traverse right
        
        traverse(node)
        return result
    
    def preorder_iterative(self, node: Optional[TreeNode] = None) -> List[int]:
        """
        Preorder traversal using iteration with a stack.
        
        Time Complexity: O(n)
        Space Complexity: O(h)
        
        Args:
            node: Starting node (defaults to root)
            
        Returns:
            List of node values in preorder
        """
        if node is None:
            node = self.root
        
        if node is None:
            return []
        
        result = []
        stack = [node]
        
        while stack:
            current = stack.pop()
            result.append(current.val)
            
            # Push right first so left is processed first
            if current.right:
                stack.append(current.right)
            if current.left:
                stack.append(current.left)
        
        return result
    
    # ==================== Inorder Traversal ====================
    
    def inorder_recursive(self, node: Optional[TreeNode] = None) -> List[int]:
        """
        Inorder traversal using recursion (Left -> Root -> Right).
        
        For BST, this produces sorted order.
        
        Time Complexity: O(n)
        Space Complexity: O(h)
        
        Args:
            node: Starting node (defaults to root)
            
        Returns:
            List of node values in inorder
            
        Example:
            >>> tree = BinaryTree.from_list([1, 2, 3, 4, 5])
            >>> tree.inorder_recursive()
            [4, 2, 5, 1, 3]
        """
        if node is None:
            node = self.root
        
        result = []
        
        def traverse(n: Optional[TreeNode]):
            if n is None:
                return
            traverse(n.left)       # Traverse left
            result.append(n.val)   # Visit root
            traverse(n.right)      # Traverse right
        
        traverse(node)
        return result
    
    def inorder_iterative(self, node: Optional[TreeNode] = None) -> List[int]:
        """
        Inorder traversal using iteration with a stack.
        
        Time Complexity: O(n)
        Space Complexity: O(h)
        
        Args:
            node: Starting node (defaults to root)
            
        Returns:
            List of node values in inorder
        """
        if node is None:
            node = self.root
        
        result = []
        stack = []
        current = node
        
        while current or stack:
            # Go to the leftmost node
            while current:
                stack.append(current)
                current = current.left
            
            # Process node
            current = stack.pop()
            result.append(current.val)
            
            # Move to right subtree
            current = current.right
        
        return result
    
    # ==================== Postorder Traversal ====================
    
    def postorder_recursive(self, node: Optional[TreeNode] = None) -> List[int]:
        """
        Postorder traversal using recursion (Left -> Right -> Root).
        
        Time Complexity: O(n)
        Space Complexity: O(h)
        
        Args:
            node: Starting node (defaults to root)
            
        Returns:
            List of node values in postorder
            
        Example:
            >>> tree = BinaryTree.from_list([1, 2, 3, 4, 5])
            >>> tree.postorder_recursive()
            [4, 5, 2, 3, 1]
        """
        if node is None:
            node = self.root
        
        result = []
        
        def traverse(n: Optional[TreeNode]):
            if n is None:
                return
            traverse(n.left)       # Traverse left
            traverse(n.right)      # Traverse right
            result.append(n.val)   # Visit root
        
        traverse(node)
        return result
    
    def postorder_iterative(self, node: Optional[TreeNode] = None) -> List[int]:
        """
        Postorder traversal using iteration with two stacks.
        
        Time Complexity: O(n)
        Space Complexity: O(h)
        
        Args:
            node: Starting node (defaults to root)
            
        Returns:
            List of node values in postorder
        """
        if node is None:
            node = self.root
        
        if node is None:
            return []
        
        result = []
        stack1 = [node]
        stack2 = []
        
        # First pass: reverse preorder (Root -> Right -> Left)
        while stack1:
            current = stack1.pop()
            stack2.append(current)
            
            if current.left:
                stack1.append(current.left)
            if current.right:
                stack1.append(current.right)
        
        # Second pass: reverse to get postorder
        while stack2:
            result.append(stack2.pop().val)
        
        return result
    
    # ==================== Level Order Traversal (Bonus) ====================
    
    def level_order(self, node: Optional[TreeNode] = None) -> List[List[int]]:
        """
        Level order traversal (BFS) - visits nodes level by level.
        
        Time Complexity: O(n)
        Space Complexity: O(w) where w is the maximum width
        
        Args:
            node: Starting node (defaults to root)
            
        Returns:
            List of lists, each containing values at that level
            
        Example:
            >>> tree = BinaryTree.from_list([1, 2, 3, 4, 5])
            >>> tree.level_order()
            [[1], [2, 3], [4, 5]]
        """
        if node is None:
            node = self.root
        
        if node is None:
            return []
        
        result = []
        queue = deque([node])
        
        while queue:
            level_size = len(queue)
            level = []
            
            for _ in range(level_size):
                current = queue.popleft()
                level.append(current.val)
                
                if current.left:
                    queue.append(current.left)
                if current.right:
                    queue.append(current.right)
            
            result.append(level)
        
        return result
    
    # ==================== Utility Methods ====================
    
    @staticmethod
    def from_list(values: List[Optional[int]]) -> 'BinaryTree':
        """
        Create a binary tree from a list (level-order representation).
        
        None values represent missing nodes.
        
        Args:
            values: List of node values in level-order
            
        Returns:
            BinaryTree instance
            
        Example:
            >>> tree = BinaryTree.from_list([1, 2, 3, 4, 5])
            >>> tree.inorder_recursive()
            [4, 2, 5, 1, 3]
        """
        if not values or values[0] is None:
            return BinaryTree(None)
        
        root = TreeNode(values[0])
        queue = deque([root])
        i = 1
        
        while queue and i < len(values):
            node = queue.popleft()
            
            # Left child
            if i < len(values) and values[i] is not None:
                node.left = TreeNode(values[i])
                queue.append(node.left)
            i += 1
            
            # Right child
            if i < len(values) and values[i] is not None:
                node.right = TreeNode(values[i])
                queue.append(node.right)
            i += 1
        
        return BinaryTree(root)
    
    def to_list(self) -> List[Optional[int]]:
        """
        Convert tree to list representation (level-order).
        
        Returns:
            List of node values with None for missing nodes
        """
        if self.root is None:
            return []
        
        result = []
        queue = deque([self.root])
        
        while queue:
            node = queue.popleft()
            
            if node:
                result.append(node.val)
                queue.append(node.left)
                queue.append(node.right)
            else:
                result.append(None)
        
        # Remove trailing None values
        while result and result[-1] is None:
            result.pop()
        
        return result
    
    def height(self, node: Optional[TreeNode] = None) -> int:
        """
        Calculate the height of the tree.
        
        Args:
            node: Starting node (defaults to root)
            
        Returns:
            Height of the tree (0 for empty tree)
        """
        if node is None:
            node = self.root
        
        if node is None:
            return 0
        
        left_height = self.height(node.left) if node.left else 0
        right_height = self.height(node.right) if node.right else 0
        return 1 + max(left_height, right_height)
    
    def size(self, node: Optional[TreeNode] = None) -> int:
        """
        Count the number of nodes in the tree.
        
        Args:
            node: Starting node (defaults to root)
            
        Returns:
            Number of nodes
        """
        if node is None:
            node = self.root
        
        if node is None:
            return 0
        
        left_size = self.size(node.left) if node.left else 0
        right_size = self.size(node.right) if node.right else 0
        return 1 + left_size + right_size


def main():
    """
    Demonstration of binary tree traversals.
    """
    print("=== Binary Tree Traversal Demo ===\n")
    
    # Create a sample tree:
    #       1
    #      / \
    #     2   3
    #    / \
    #   4   5
    
    tree = BinaryTree.from_list([1, 2, 3, 4, 5])
    
    print("Tree structure (level-order):", tree.to_list())
    print(f"Tree height: {tree.height()}")
    print(f"Tree size: {tree.size()}")
    print()
    
    # Preorder traversal
    print("Preorder Traversal (Root -> Left -> Right):")
    print("  Recursive:", tree.preorder_recursive())
    print("  Iterative:", tree.preorder_iterative())
    print()
    
    # Inorder traversal
    print("Inorder Traversal (Left -> Root -> Right):")
    print("  Recursive:", tree.inorder_recursive())
    print("  Iterative:", tree.inorder_iterative())
    print()
    
    # Postorder traversal
    print("Postorder Traversal (Left -> Right -> Root):")
    print("  Recursive:", tree.postorder_recursive())
    print("  Iterative:", tree.postorder_iterative())
    print()
    
    # Level order traversal
    print("Level Order Traversal (BFS):")
    print("  ", tree.level_order())
    print()
    
    # Another example with a larger tree
    print("=== Larger Tree Example ===\n")
    tree2 = BinaryTree.from_list([1, 2, 3, 4, 5, 6, 7, 8, 9])
    print("Tree structure:", tree2.to_list())
    print("Inorder:", tree2.inorder_recursive())
    print("Preorder:", tree2.preorder_recursive())
    print("Postorder:", tree2.postorder_recursive())


if __name__ == "__main__":
    main()
