"""
Fibonacci Number Calculator

This module provides multiple implementations for calculating Fibonacci numbers,
including recursive, iterative, and generator-based approaches.

Author: Generated by OpenClaw
Date: 2026-03-02
"""

from typing import Generator, List


def fibonacci_recursive(n: int) -> int:
    """
    Calculate the nth Fibonacci number using recursion.
    
    This is the most intuitive implementation but has exponential time complexity O(2^n).
    Not recommended for large values of n.
    
    Args:
        n: The position in the Fibonacci sequence (0-indexed)
        
    Returns:
        The nth Fibonacci number
        
    Raises:
        ValueError: If n is negative
        
    Examples:
        >>> fibonacci_recursive(0)
        0
        >>> fibonacci_recursive(1)
        1
        >>> fibonacci_recursive(10)
        55
    """
    if n < 0:
        raise ValueError("n must be non-negative")
    if n <= 1:
        return n
    return fibonacci_recursive(n - 1) + fibonacci_recursive(n - 2)


def fibonacci_iterative(n: int) -> int:
    """
    Calculate the nth Fibonacci number using iteration.
    
    This implementation has linear time complexity O(n) and constant space complexity O(1).
    Recommended for most use cases.
    
    Args:
        n: The position in the Fibonacci sequence (0-indexed)
        
    Returns:
        The nth Fibonacci number
        
    Raises:
        ValueError: If n is negative
        
    Examples:
        >>> fibonacci_iterative(0)
        0
        >>> fibonacci_iterative(1)
        1
        >>> fibonacci_iterative(10)
        55
    """
    if n < 0:
        raise ValueError("n must be non-negative")
    if n <= 1:
        return n
    
    a, b = 0, 1
    for _ in range(2, n + 1):
        a, b = b, a + b
    return b


def fibonacci_sequence(n: int) -> List[int]:
    """
    Generate a list of the first n Fibonacci numbers.
    
    Args:
        n: Number of Fibonacci numbers to generate
        
    Returns:
        List of the first n Fibonacci numbers
        
    Raises:
        ValueError: If n is negative
        
    Examples:
        >>> fibonacci_sequence(5)
        [0, 1, 1, 2, 3]
        >>> fibonacci_sequence(10)
        [0, 1, 1, 2, 3, 5, 8, 13, 21, 34]
    """
    if n < 0:
        raise ValueError("n must be non-negative")
    if n == 0:
        return []
    if n == 1:
        return [0]
    
    sequence = [0, 1]
    for i in range(2, n):
        sequence.append(sequence[i - 1] + sequence[i - 2])
    return sequence


def fibonacci_generator(n: int) -> Generator[int, None, None]:
    """
    Generate Fibonacci numbers up to the nth number using a generator.
    
    This is memory-efficient as it yields numbers one at a time.
    
    Args:
        n: Number of Fibonacci numbers to generate
        
    Yields:
        Fibonacci numbers one at a time
        
    Raises:
        ValueError: If n is negative
        
    Examples:
        >>> list(fibonacci_generator(5))
        [0, 1, 1, 2, 3]
        >>> for num in fibonacci_generator(10):
        ...     print(num, end=' ')
        0 1 1 2 3 5 8 13 21 34
    """
    if n < 0:
        raise ValueError("n must be non-negative")
    
    a, b = 0, 1
    for _ in range(n):
        yield a
        a, b = b, a + b


def main():
    """
    Demonstration of different Fibonacci implementations.
    """
    print("=== Fibonacci Number Calculator ===\n")
    
    # Example 1: Calculate specific Fibonacci numbers
    print("1. Calculate specific Fibonacci numbers:")
    for i in [0, 1, 5, 10, 15]:
        result = fibonacci_iterative(i)
        print(f"   F({i}) = {result}")
    
    print("\n2. Generate Fibonacci sequence:")
    sequence = fibonacci_sequence(10)
    print(f"   First 10 numbers: {sequence}")
    
    print("\n3. Using generator (memory-efficient):")
    print("   First 15 numbers:", end=" ")
    for num in fibonacci_generator(15):
        print(num, end=" ")
    print()
    
    print("\n4. Compare recursive vs iterative (for small n):")
    n = 10
    recursive_result = fibonacci_recursive(n)
    iterative_result = fibonacci_iterative(n)
    print(f"   Recursive F({n}) = {recursive_result}")
    print(f"   Iterative F({n}) = {iterative_result}")
    print(f"   Results match: {recursive_result == iterative_result}")


if __name__ == "__main__":
    main()
