"""
Linked List Implementation

This module provides a complete singly linked list data structure with common operations.

Author: Generated by 小fancy
Date: 2026-03-02
"""

from typing import Optional, List, Any


class ListNode:
    """
    Singly linked list node.
    
    Attributes:
        val: The value stored in the node
        next: Reference to the next node
    """
    
    def __init__(self, val: Any = 0, next: Optional['ListNode'] = None):
        """
        Initialize a list node.
        
        Args:
            val: Node value
            next: Next node reference
        """
        self.val = val
        self.next = next
    
    def __repr__(self) -> str:
        return f"ListNode({self.val})"


class LinkedList:
    """
    Singly linked list with common operations.
    """
    
    def __init__(self):
        """Initialize an empty linked list."""
        self.head: Optional[ListNode] = None
        self._size: int = 0
    
    def __len__(self) -> int:
        """Return the number of nodes in the list."""
        return self._size
    
    def __repr__(self) -> str:
        """String representation of the list."""
        values = []
        current = self.head
        while current:
            values.append(str(current.val))
            current = current.next
        return " -> ".join(values) if values else "Empty"
    
    def is_empty(self) -> bool:
        """
        Check if the list is empty.
        
        Returns:
            True if empty, False otherwise
        """
        return self.head is None
    
    # ==================== Insertion Operations ====================
    
    def insert_at_head(self, val: Any) -> None:
        """
        Insert a new node at the head of the list.
        
        Time Complexity: O(1)
        
        Args:
            val: Value to insert
            
        Example:
            >>> ll = LinkedList()
            >>> ll.insert_at_head(1)
            >>> ll.insert_at_head(2)
            >>> print(ll)
            2 -> 1
        """
        new_node = ListNode(val, self.head)
        self.head = new_node
        self._size += 1
    
    def insert_at_tail(self, val: Any) -> None:
        """
        Insert a new node at the tail of the list.
        
        Time Complexity: O(n)
        
        Args:
            val: Value to insert
        """
        new_node = ListNode(val)
        
        if self.head is None:
            self.head = new_node
        else:
            current = self.head
            while current.next:
                current = current.next
            current.next = new_node
        
        self._size += 1
    
    def insert_at_position(self, val: Any, position: int) -> bool:
        """
        Insert a new node at the specified position.
        
        Time Complexity: O(n)
        
        Args:
            val: Value to insert
            position: Position to insert at (0-indexed)
            
        Returns:
            True if successful, False if position is invalid
        """
        if position < 0 or position > self._size:
            return False
        
        if position == 0:
            self.insert_at_head(val)
            return True
        
        new_node = ListNode(val)
        current = self.head
        
        for _ in range(position - 1):
            current = current.next
        
        new_node.next = current.next
        current.next = new_node
        self._size += 1
        return True
    
    # ==================== Deletion Operations ====================
    
    def delete_at_head(self) -> Optional[Any]:
        """
        Delete the head node and return its value.
        
        Time Complexity: O(1)
        
        Returns:
            Value of deleted node, or None if list is empty
        """
        if self.head is None:
            return None
        
        val = self.head.val
        self.head = self.head.next
        self._size -= 1
        return val
    
    def delete_at_tail(self) -> Optional[Any]:
        """
        Delete the tail node and return its value.
        
        Time Complexity: O(n)
        
        Returns:
            Value of deleted node, or None if list is empty
        """
        if self.head is None:
            return None
        
        if self.head.next is None:
            val = self.head.val
            self.head = None
            self._size -= 1
            return val
        
        current = self.head
        while current.next.next:
            current = current.next
        
        val = current.next.val
        current.next = None
        self._size -= 1
        return val
    
    def delete_by_value(self, val: Any) -> bool:
        """
        Delete the first node with the specified value.
        
        Time Complexity: O(n)
        
        Args:
            val: Value to delete
            
        Returns:
            True if deleted, False if not found
        """
        if self.head is None:
            return False
        
        if self.head.val == val:
            self.head = self.head.next
            self._size -= 1
            return True
        
        current = self.head
        while current.next:
            if current.next.val == val:
                current.next = current.next.next
                self._size -= 1
                return True
            current = current.next
        
        return False
    
    # ==================== Search Operations ====================
    
    def find(self, val: Any) -> Optional[ListNode]:
        """
        Find the first node with the specified value.
        
        Time Complexity: O(n)
        
        Args:
            val: Value to find
            
        Returns:
            Node if found, None otherwise
        """
        current = self.head
        while current:
            if current.val == val:
                return current
            current = current.next
        return None
    
    def get_at_position(self, position: int) -> Optional[Any]:
        """
        Get the value at the specified position.
        
        Time Complexity: O(n)
        
        Args:
            position: Position to get (0-indexed)
            
        Returns:
            Value at position, or None if invalid
        """
        if position < 0 or position >= self._size:
            return None
        
        current = self.head
        for _ in range(position):
            current = current.next
        
        return current.val
    
    # ==================== Reversal Operations ====================
    
    def reverse(self) -> None:
        """
        Reverse the linked list in-place.
        
        Time Complexity: O(n)
        Space Complexity: O(1)
        
        Example:
            >>> ll = LinkedList.from_list([1, 2, 3, 4])
            >>> ll.reverse()
            >>> print(ll)
            4 -> 3 -> 2 -> 1
        """
        prev = None
        current = self.head
        
        while current:
            next_node = current.next
            current.next = prev
            prev = current
            current = next_node
        
        self.head = prev
    
    def reverse_recursive(self) -> None:
        """
        Reverse the linked list recursively.
        
        Time Complexity: O(n)
        Space Complexity: O(n) due to recursion stack
        """
        def _reverse(node: Optional[ListNode], prev: Optional[ListNode] = None) -> Optional[ListNode]:
            if node is None:
                return prev
            
            next_node = node.next
            node.next = prev
            return _reverse(next_node, node)
        
        self.head = _reverse(self.head)
    
    # ==================== Utility Methods ====================
    
    def to_list(self) -> List[Any]:
        """
        Convert linked list to Python list.
        
        Returns:
            List of values
        """
        result = []
        current = self.head
        while current:
            result.append(current.val)
            current = current.next
        return result
    
    @staticmethod
    def from_list(values: List[Any]) -> 'LinkedList':
        """
        Create a linked list from a Python list.
        
        Args:
            values: List of values
            
        Returns:
            LinkedList instance
            
        Example:
            >>> ll = LinkedList.from_list([1, 2, 3, 4])
            >>> print(ll)
            1 -> 2 -> 3 -> 4
        """
        ll = LinkedList()
        for val in values:
            ll.insert_at_tail(val)
        return ll
    
    def clear(self) -> None:
        """Clear all nodes from the list."""
        self.head = None
        self._size = 0
    
    def has_cycle(self) -> bool:
        """
        Detect if the linked list has a cycle using Floyd's algorithm.
        
        Time Complexity: O(n)
        Space Complexity: O(1)
        
        Returns:
            True if cycle exists, False otherwise
        """
        if self.head is None:
            return False
        
        slow = self.head
        fast = self.head
        
        while fast and fast.next:
            slow = slow.next
            fast = fast.next.next
            
            if slow == fast:
                return True
        
        return False
    
    def get_middle(self) -> Optional[Any]:
        """
        Get the middle element of the list.
        
        Time Complexity: O(n)
        Space Complexity: O(1)
        
        Returns:
            Value of middle node, or None if empty
        """
        if self.head is None:
            return None
        
        slow = self.head
        fast = self.head
        
        while fast.next and fast.next.next:
            slow = slow.next
            fast = fast.next.next
        
        return slow.val


def main():
    """
    Demonstration of linked list operations.
    """
    print("=== Linked List Demo ===\n")
    
    # Create a linked list
    ll = LinkedList()
    print("1. Creating empty list:")
    print(f"   {ll}")
    print(f"   Size: {len(ll)}")
    print()
    
    # Insert at head
    print("2. Insert at head: 3, 2, 1")
    ll.insert_at_head(3)
    ll.insert_at_head(2)
    ll.insert_at_head(1)
    print(f"   {ll}")
    print()
    
    # Insert at tail
    print("3. Insert at tail: 4, 5")
    ll.insert_at_tail(4)
    ll.insert_at_tail(5)
    print(f"   {ll}")
    print()
    
    # Insert at position
    print("4. Insert 10 at position 2:")
    ll.insert_at_position(10, 2)
    print(f"   {ll}")
    print()
    
    # Search
    print("5. Search for value 10:")
    node = ll.find(10)
    print(f"   Found: {node}")
    print()
    
    # Get at position
    print("6. Get value at position 3:")
    val = ll.get_at_position(3)
    print(f"   Value: {val}")
    print()
    
    # Delete operations
    print("7. Delete at head:")
    deleted = ll.delete_at_head()
    print(f"   Deleted: {deleted}")
    print(f"   List: {ll}")
    print()
    
    print("8. Delete by value (10):")
    success = ll.delete_by_value(10)
    print(f"   Success: {success}")
    print(f"   List: {ll}")
    print()
    
    # Reverse
    print("9. Reverse the list:")
    ll.reverse()
    print(f"   {ll}")
    print()
    
    # Get middle
    print("10. Get middle element:")
    middle = ll.get_middle()
    print(f"   Middle: {middle}")
    print()
    
    # Convert to list
    print("11. Convert to Python list:")
    py_list = ll.to_list()
    print(f"   {py_list}")
    print()
    
    # Create from list
    print("12. Create new list from [10, 20, 30, 40, 50]:")
    ll2 = LinkedList.from_list([10, 20, 30, 40, 50])
    print(f"   {ll2}")
    print(f"   Size: {len(ll2)}")
    print()
    
    # Cycle detection
    print("13. Cycle detection:")
    print(f"   Has cycle: {ll2.has_cycle()}")


if __name__ == "__main__":
    main()
